background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    fade_on_empty = false
}

label {
    monitor =
    text = $TIME
    font_size = 50
    position = 0, 80
    halign = center
    valign = center
}
