general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita abrir o hyprlock duas vezes
    before_sleep_cmd = loginctl lock-session    # Tranca a tela caso você use o S-Sh-Q
    after_sleep_cmd = hyprctl dispatch dpms on  # Garante que a tela acenda ao voltar
}

listener {
    timeout = 180
    on-timeout = loginctl lock-session
}
