workspace=1,monitor:desc:BOE 0x0AFC,default:true
workspace=4,monitor:desc:BOE 0x0AFC
workspace=7,monitor:desc:BOE 0x0AFC

workspace=2,monitor:desc:AOC 22B30HM23 230P7XA014010,default:true
workspace=5,monitor:desc:AOC 22B30HM23 230P7XA014010
workspace=8,monitor:desc:AOC 22B30HM23 230P7XA014010

workspace=3,monitor:desc:AOC 22B30HM23 230P8XA006845,default:true
workspace=6,monitor:desc:AOC 22B30HM23 230P8XA006845
workspace=9,monitor:desc:AOC 22B30HM23 230P8XA006845
workspace=10,monitor:desc:AOC 22B30HM23 230P8XA006845
