# Deslizar 3 dedos para a esquerda -> Próximo Workspace ativo
gesture swipe left 3 hyprctl dispatch workspace e+1

# Deslizar 3 dedos para a direita -> Workspace ativo anterior
gesture swipe right 3 hyprctl dispatch workspace e-1

# Deslizar 3 dedos para baixo -> Scratchpad
gesture swipe down 3 hyprctl dispatch togglespecialworkspace scratchpad

# Mapeamento do gesto para o Hyprspace
gesture swipe up 3 hyprctl dispatch overview:toggle
